include ~/sw/hsc3-data/mk/dx7.mk

C = SYNTECH-0 SYNTECH-1 SYNTECH-2 SYNTECH-3 SYNTECH-4 SYNTECH-5 SYNTECH-6 SYNTECH-7 SYNTECH-8 SYNTECH-9

all: $(C:=.syx.text) $(C:=.syx.names.text) $(C:=.syx.param.text)

clean:
	rm -f *.text
