P=$(HOME)/data/chemistry
Q=$(HOME)/sw/hsc3-data/data/chemistry

ln-local:
	rm -f $(Q)/aflow/poscar $(Q)/cls/xyz $(Q)/mp/poscar
	ln -s $(P)/aflow/poscar $(Q)/aflow
	ln -s $(P)/cls/xyz $(Q)/cls
	ln -s $(P)/mp/poscar $(Q)/mp
