cmd =	au-to-png \
	csv-mnd-to-pgm \
	img-edit img-to-pbm img-to-pgm img-to-sf img-to-tbl \
	pbm-indices \
	pgm-to-au \
	midi-to-csv-mnd midi-to-text \
	sf-condense sf-draw sf-to-img \
	trace-rec-x11

include ~/sw/hsc3/mk/cmd.mk
